website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(50), unique=True)
    password = db.Column(db.String(50))
    first_name = db.Column(db.String(50))
    date = db.Column(db.DateTime(timezone=True), default=func.now())

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'topsecretkey!'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User
    
    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db  # means from __init__.py import db
from flask_login import login_user, login_required, logout_user, current_user
from sqlalchemy.sql import func


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        # get user from html form
        email = request.form.get('email')
        password = request.form.get('password')
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.home'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        # get user from html form
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        # find user in db by email
        user = User.query.filter_by(email=email).first()
        # if user is valid add to db
        if user and len(email) > 5:
            flash('Email already exists.', category='error')
        elif validateUser(email,first_name,password1,password2):
            new_user = User(email=email, first_name=first_name,
                            password=generate_password_hash(
                                password1, method='sha256'),
                            date=func.now())
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))
    return render_template("sign_up.html", user=current_user)



def validateUser(email,first_name,password1,password2):
        if len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
            return False
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
            return False
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
            return False
        elif len(password1) < 4:
            flash('Password must be at least 4 characters.', category='error')
            return False
        return True

website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, Response
from flask_login import login_required, current_user
from .models import User
from .camera import gen_frames
from . import db  # means from __init__.py import db

# for versions
import platform
import sys
import flask
import flask_login
import flask_sqlalchemy
import tensorflow
import numpy
import cv2

views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
def home():
    return render_template("home.html", user=current_user)


@views.route('/about')
def about():

    return render_template("about.html", user=current_user,
                        platform_systm=platform.system(),
                        platform_version=platform.release(),
                        platform_architecture=platform.machine(),
                        platform_network=platform.node(),
                        platform_processor=platform.processor(),
                        python_version=sys.version,
                        flask_version=flask.__version__,
                        flask_sqlalchemy_version=flask_sqlalchemy.__version__,
                        flask_login_version=flask_login.__version__,
                        tensorflow_version=tensorflow.__version__,
                        numpy_version=numpy.__version__,
                        opencv_version=cv2.__version__
    )

@views.route('/start')
@login_required
def start():
    cameraOn = True
    return render_template("start.html", user=current_user, cameraOn=cameraOn)


@views.route('/users')
@login_required
def users():
    users = User.query.all()
    return render_template("users.html", user=current_user, users=users)


@views.route('/video_feed')
@login_required
def video_feed():

    return Response(gen_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')

website/templates/about.html
{% extends "base.html" %}
{% block title %}About{% endblock %}
{% block content%}

<h2 class="mt-4 mb-2">Environment Info</h2>

<table class="table table-hover">
    <thead>

    </thead>
    <tbody>
        <tr>
            <th>Platform System</th>
        <td>{{ platform_systm }}</td>
    </tr>
    <tr>
        <th>Platform Version</th>
        <td>{{ platform_version }}</td>
    </tr>
    <tr>
        <th>Platform Architecture</th>
        <td>{{ platform_architecture }}</td>
    </tr>
    <tr>
        <th>Platform Network</th>
        <td>{{ platform_network }}</td>
    </tr>
    <tr>
        <th>Platform Processor</th>
        <td>{{ platform_processor }}</td>
    </tr>
    <tr>
        <th>Python Version</th>
        <td>{{ python_version }}</td>
    </tr>
    <tr>
        <th>Flask Version</th>
        <td>{{ flask_version }}</td>
    </tr>
    <tr>
        <th>Flask-SQLAlchemy Version</th>
        <td>{{ flask_sqlalchemy_version }}</td>
    </tr>
    <tr>
        <th>Flask-Login Version</th>
        <td>{{ flask_login_version }}</td>
    </tr>
    <tr>
        <th>TensorFlow Version</th>
        <td>{{ tensorflow_version }}</td>
    </tr>
    <tr>
        <th>NumPy Version</th>
        <td>{{ numpy_version }}</td>
    </tr>
    <tr>
        <th>OpenCV Version</th>
        <td>{{ opencv_version }}</td>
    </tr>
</tbody>
</table>


{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en-US" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!--    Document Title-->
  <title> {% block title %} {% endblock %} - Human Fall Detection</title>

  <!--    Favicon-->
  <link rel="shortcut icon" type="image/x-icon" href="../static/assets/img/favicons/favicon.png">
  <meta name="theme-color" content="#ffffff">

  <!--    Stylesheets-->
  <link href="../static/assets/css/theme.css" rel="stylesheet" />

</head>


<body>

  <main class="main" id="top">

    <!--! Navbar begin  -->
    <nav class="navbar navbar-expand-lg navbar-light sticky-top" data-navbar-on-scroll="data-navbar-on-scroll">
      <div class="container">
        <a class="navbar-brand fw-bold fs-3" href="/">
          <i class="fa-solid fa-person-falling fa-xl"></i>
          Human Fall Detection</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
            class="navbar-toggler-icon">
          </span></button>
        <div class="collapse navbar-collapse border-top border-lg-0 mt-4 mt-lg-0" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item"><a class="nav-link" aria-current="page" href="/">Home</a></li>
            <li class="nav-item"><a class="nav-link" aria-current="page" href="/start">Control Panel</a>
            </li>
            <li class="nav-item"><a class="nav-link" aria-current="page" href="/users">Users</a></li>
            <li class="nav-item"><a class="nav-link" aria-current="page" href="/about">About</a></li>
          </ul>

          <div class="d-flex ms-lg-4 ">
            {% if user.is_authenticated %}
            <a class="btn me-1 " > Welcome,  {{user.first_name}} </a>
            <a class="btn btn-warning" id="logout" href="/logout">Logout <i
              class="fa-solid fa-arrow-right-to-bracket"></i> </a>
            {% else %}
            <a class="btn btn-secondary-outline" href="/login">Login</a>
            <a class="btn btn-warning ms-3" href="/sign-up">Sign Up</a>
            {% endif %}
          </div>


        </div>

      </div>
    </nav>
    <!--! Navbar end  -->


    <!--! alerts -->
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    {% if category =='error' %}
    <div class="alert alert-dismissible alert-danger">
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
      {{message}}
    </div>
    {% else %}
    <div class="alert alert-dismissible alert-success ">
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
      {{message}}
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}
    <!--! alerts -->


    <div class="container">{% block content %} {% endblock %}</div>




    <!--! Footer begin  -->
    <div id="footer">
      <section class="pb-2 pb-lg-5">

        <div class="container">
          <div class="row border-top border-top-secondary pt-7">
            <div class=" col-md-6 mb-4 mb-md-6 mb-lg-0 mb-sm-2 order-1 order-md-1 order-lg-1">

              <a class="navbar-brand fw-bold fs-3 " href="/">
                <i class="fa-solid fa-person-falling fa-xl"></i>
                Human Fall Detection</a>
            </div>
            <div class="col-lg-3 col-md-6 mb-4 mb-lg-0 order-3 order-md-3 order-lg-2">
              <p class="fs-2 mb-lg-4">Quick Links</p>
              <ul class="list-unstyled mb-0">
                <li class="mb-1"><a class="link-900 text-secondary text-decoration-none" href="#home">Home</a></li>
                <li class="mb-1"><a class="link-900 text-secondary text-decoration-none" href="#features">Features</a>
                </li>
                <li class="mb-1"><a class="link-900 text-secondary text-decoration-none" href="#risks">Risks</a></li>
                <li class="mb-1"><a class="link-900 text-secondary text-decoration-none"
                    href="#acknowledgements">Acknowledgements</a></li>
              </ul>
            </div>
            <div class="col-lg-3 col-md-6 mb-4 mb-lg-0 order-4 order-md-4 order-lg-3">
              <p class="fs-2 mb-lg-4">Legal stuff</p>
              <ul class="list-unstyled mb-0">
                <li class="mb-1"><a class="link-900 text-secondary text-decoration-none" href="#!">Disclaimer</a></li>
                <li class="mb-1"><a class="link-900 text-secondary text-decoration-none" href="#!">Financing</a></li>
                <li class="mb-1"><a class="link-900 text-secondary text-decoration-none" href="#!">Privacy
                    Policy</a></li>
                <li class="mb-1"><a class="link-900 text-secondary text-decoration-none" href="#!">Terms
                    of
                    Service</a>
                </li>
              </ul>
            </div>

          </div>
        </div><!-- end of .container-->

      </section>

      <section class="text-center py-0">
        <div class="container">
          <div class="container border-top py-3">
            <div class="row justify-content-between">
              <div class="col-12 col-md-auto mb-1 mb-md-0">
                <p class="mb-0"> Graduation Project 2023-2024 </p>
              </div>
              <div class="col-12 col-md-auto">
                <p class="mb-0">
                  Made By Abanob Raffet</p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    <!--! Footer end  -->


  </main>

  <!-- ===============================================-->
  <!--    JavaScripts-->
  <!-- ===============================================-->
  <script src="https://kit.fontawesome.com/d71a54271d.js" crossorigin="anonymous"></script>
  <script src="../static/vendors/@popperjs/popper.min.js"></script>
  <script src="../static/vendors/bootstrap/bootstrap.min.js"></script>
  <script src="../static/vendors/is/is.min.js"></script>
  <script src="https://polyfill.io/v3/polyfill.min.js?features=window.scroll"></script>
  <script src="../static/vendors/fontawesome/all.min.js"></script>
  <script src="../static/assets/js/theme.js"></script>
  <script src="../static/vendors/JQuery/jquery-3.7.1.min.js.js"></script>
 
  {% block jquery %}
  {% endblock %}

  <link
    href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&amp;family=Volkhov:wght@700&amp;display=swap"
    rel="stylesheet">
</body>

</html>

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<form method="POST">
  <h3 align="center">Login</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}
<form method="POST">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter first name"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

website/templates/start.html
{% extends "base.html" %}
{% block title %}Control Panel{% endblock %}
{% block content%}


<div class="alert alert-dismissible alert-success " style="display: none;">
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    Please wait the model is loading
</div>

<!-- camera -->
<section class="pt-5" id="Camera">
    <div class="bg-holder z-index--1 bottom-0 d-none d-lg-block background-position-top"
        style="background-image:url(../static/assets/img/superhero/oval.png);opacity:.5; background-position: top !important ;">
    </div>
    <!--/.bg-holder-->


    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h4 class="fs-1 fw-bold">MoveNet Model</h4>
                <p class="mb-4 fw-medium text-secondary">
                    The MoveNet model is a deep neural network that uses convolutional layers to detect human
                    body keypoints and pose landmarks in images or videos.
                    <br><br> For better result switch to the more acurate model <br> (make sure you have a
                    modern nividia gpu)
                </p>
                <form>
                    <div>
                        <label class="form-label">Choose Your Camera</label>
                        <select class="form-select">
                            <option>Default Camera</option>
                            <option>Camera 2</option>
                        </select>
                    </div>
                    <div>
                        <label class="form-label mt-2 ">Alert Type</label>
                        <select class="form-select">
                            <option>Sound</option>
                            <option>Picture</option>
                            <option>Sound and Picture</option>
                        </select>
                    </div>

                    <button class="btn btn-success mt-3">Apply Settings</button>
                </form>
            </div>
            <div class="col-lg-6 row">
                <img id="camera_placeholder" src="../static/assets/img/cameraplaceholder.png" />
                <p class="text-danger mt-3 ">the quality of the video stream and fall detection depends on your
                    device hardware</p>
                <button id="toggler" class="btn btn-primary">Toggle Camera On and Off</button>

            </div>

        </div>
    </div><!-- end of .container-->

</section>
<!-- camera -->
{% endblock %}

{% block jquery %}
<script>
    $('.alert').hide()
    $('#toggler').click(function () {
        let current_src = $('#camera_placeholder').attr('src');
        if (current_src == '../static/assets/img/cameraplaceholder.png') {
            $('.alert').show()
            $('#camera_placeholder').attr('src', "{{url_for('views.video_feed')}}")
        } else {
            $('.alert').hide()
            $('#camera_placeholder').attr('src', "../static/assets/img/cameraplaceholder.png")
        }
    })
</script>
{% endblock %}